#!/bin/bash

# The usage of the script is for assigment 1 in virtual and sets static IP-adresses to the assigned networkcard

IP1=192.168.0.10/24
IP2=192.168.1.10/24

echo "network:
    version: 2
    renderer: networkd
    ethernets:
        ens160:
            dhcp4: yes
	    ens192:
	        dhcp4: no
	        addresses: [$IP1]
	    ens224:
	        dhcp: no
	        addresses: [$IP2]" 
>> /etc/netplan/netplanconf
