#!/bin/bash
#This bash-script is made for a particular assigment where you install and configure zfs and share it like nfs.
#this commands needs to be in root (sudo -i)
# using sleep as a debug tool, you can remove it of you want
 
#install required packages for the assigment
apt update -y
apt install -y zfsutils-linux 
apt install -y nfs-kernel-server
apt install -y targetcli-fb
#makes a copy of old config file
cp /etc/netplan/01-netcfg.yaml /etc/netplan/01-netcfg.yaml.bak
#running script for setting static IP-addresses on ens192,ens224 check netplanscript
sh ./netplanscript
netplan apply
ifconfig -a
sleep 5
#making directory for txt files that are captured during the script
mkdir /etc/notes
zpool list
lsblk
zpool create tank mirror /dev/sdb /dev/sdc
zfs list
zfs create tank/home
fdisk -l >> /etc/notes/tempanswer.txt
zpool add tank mirror /dev/sdd /dev/sde
zpool list -v 
zfs create tank/temp
zfs list >> /etc/notes/homevstemp.txt
cd /tank/temp
dd if=/dev/zero of=100mb-file bs=1000000 count=105
echo "100MB FILE CREATED"
sleep 2
cd /
zfs get all tank/temp
zfs set refquota=500M tank/temp
zfs list >> /etc/notes/quota.txt
zfs snapshot tank/temp@first
echo "SNAPSHOT TAKEN"
sleep 2
zfs list -t snapshot
zfs set snapdir=visible tank/temp
ls -al /tank/temp/.zfs
rm -rf /tank/temp/*
zfs list -t snapshot >> /etc/notes/snapshot.txt
ls -al /tank/temp/
zfs rollback tank/temp@first
zfs destroy -r tank/home
zfs destroy -r tank/temp
zpool destroy tank
echo "FILESYSTEM & POOLS ARE DESTROYED"
sleep 2
zpool create -f exports raidz /dev/sdb /dev/sdc /dev/sdd /dev/sde
zfs create exports/nfs
echo "RAIDZ1 & FILESYSTEM CREATED"
sleep 1

#vim $(find -name exports)
echo "/exports/nfs      *(rw,no_root_squash,async)" >> /etc/exports 
mount -t nfs 10.206.19.*:/exports/nfs /mnt
echo "ROWS CREATED IN /ETC/EXPORTS & DISK MOUNTED"
lsblk
sleep 2
df -h >> /etc/notes/mounted.txt
useradd -m -u 1010 alice
touch /exports/nfs/alice_file
chown alice:alice /exports/nfs/alice_file
echo "TASK 1-26 ARE FINISH"

#configure local disk as iscsi and export to remote system
#task 27

targetcli
cd
create
